version: '3.8'
services:
  backend:
    build: ./BE
    ports:
      - "8000:8000"
    volumes:
      - ./BE/uploads:/app/uploads
      - ./BE/serviceAccountKey.json:/app/serviceAccountKey.json
    env_file:
      - ./BE/.env

  frontend:
    build: ./FE
    ports:
      - "3000:3000"
    depends_on:
      - backend