name: Docker Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Backend
        run: docker build ./BE -t quizai-backend

      - name: Build Frontend
        run: docker build ./FE -t quizai-frontend